#!/bin/bash
#: Title:	: terbling
#: Author	: clewsy (clewsy.pro)
#: Description	: Just show the logo and some basic system info.
#: Options	: None.

## Exit codes.
SUCCESS=0
BAD_ARGUMENT=1

## Define colours and formatting.
BLACK="\\033[00;30m"
RED="\\033[00;31m"
ORANGE="\\033[00;38;5;214m"
GREEN="\\033[00;32m"
YELLOW="\\033[00;33m"
BLUE="\\033[00;34m"
MAGENTA="\\033[00;35m"
CYAN="\\033[00;36m"
GRAY="\\033[00;40m"
WHITE="\\033[00;37m"

BOLD="\\033[1m"
DIM="\\033[2m"
RESET="\\033[0m"

## Set theme colour.
DEFAULT_COL="${CYAN}"

## Ensure no more than 1 argument was entered.
if (( $# > 1 )); then
	printf "%b" "${RED}Error:${RESET} Invalid argument.\n"
	printf "%b" "${USAGE}\n"
	exit $BAD_ARGUMENT
fi

## Parse the first argument to set the theme colour.
case $1 in
	"BLACK" 	| "black")	COL="${BLACK}";;
	"RED"		| "red")	COL="${RED}";;
	"ORANGE"	| "orange")	COL="${ORANGE}";;
	"GREEN"		| "green")	COL="${GREEN}";;
	"YELLOW"	| "yellow")	COL="${YELLOW}";;
	"BLUE"		| "blue")	COL="${BLUE}";;
	"MAGENTA"	| "magenta")	COL="${MAGENTA}";;
	"CYAN"		| "cyan")	COL="${CYAN}";;
	"GRAY"		| "gray")	COL="${GRAY}";;
	"GREY"		| "grey")	COL="${GRAY}";;
	"WHITE"		| "white")	COL="${WHITE}";;
	*)				COL="${DEFAULT_COL}";;
esac

####################################################################################################################################
## Bios info
BIOS_DATE=$(cat /sys/devices/virtual/dmi/id/bios_date)
BIOS_VERSION=$(cat /sys/devices/virtual/dmi/id/bios_version)
BIOS_VENDOR=$(cat /sys/devices/virtual/dmi/id/bios_vendor)
S01="${BOLD}Bios:${RESET} ${BIOS_DATE}, version ${BIOS_VERSION} (${BIOS_VENDOR})"

####################################################################################################################################
## CPU info
CPU_MODEL=$(lscpu | grep -m 1 -e "Model name:" | sed 's/Model name: *//')
CPU_VENDOR=$(lscpu | grep -m 1 -e "Vendor ID:" | sed 's/Vendor ID: *//')
CPU_ARCH=$(lscpu | grep -m 1 -e "Architecture:" | sed 's/Architecture: *//')
CPU_MODE=$(lscpu | grep -m 1 -e "CPU op-mode(s):" | sed 's/CPU op-mode(s): *//')
CPU_CORES=$(lscpu | grep -m 1 -e "CPU(s):" | sed 's/CPU(s): *//')
CPU_SPEED=$(lscpu | grep -m 1 -e "CPU MHz:" | sed 's/CPU MHz: *//')
CPU_MAX_SPEED=$(lscpu | grep -m 1 -e "CPU max MHz:" | sed 's/CPU max MHz: *//')
CPU_MIN_SPEED=$(lscpu | grep -m 1 -e "CPU min MHz:" | sed 's/CPU min MHz: *//')

S02="${BOLD}Processor:${RESET}"
S03="--Model:${RESET} ${CPU_MODEL}"
S04="--Vendor:${RESET} ${CPU_VENDOR}"
S05="--Architecture:${RESET} ${CPU_ARCH}"
S06="--Mode(s):${RESET} ${CPU_MODE}"
S07="--Cores:${RESET} ${CPU_CORES}"
S08="--Speed:${RESET} ${CPU_SPEED}MHz"
S09="--Max Speed:${RESET} ${CPU_MAX_SPEED}MHz"
S10="--Min Speed:${RESET} ${CPU_MIN_SPEED}MHz"

####################################################################################################################################
## OS kernel and distribution info
S11="${BOLD}Operating System:${RESET}"
S12="--OS:${RESET} $(uname -o)"
S13="--Architecture:${RESET} $(uname -m)"
S14="--Kernel:${RESET} $(uname -s)"
S15="${DIM}----Version:${RESET} $(uname -v)"
S16="${DIM}----Release:${RESET} $(uname -r)"
S17="--Distribution:${RESET} $(grep -e "^PRETTY_NAME=" /etc/os-release | cut -d "\"" -f 2)"
S18="${DIM}----Version:${RESET} $(grep -e "^VERSION=" /etc/os-release | cut -d "\"" -f 2)"
S19="${DIM}----ID:${RESET} $(grep -e "^ID=" /etc/os-release | cut -d "=" -f 2)"
S20="${DIM}----Codename:${RESET} $(lsb_release -c | cut -f2)"

####################################################################################################################################
## Output
printf "%b" "
${COL}${BOLD}               ____	    ${S01}
${COL}${BOLD}              /   /    /\    ${S02}
${COL}${BOLD}             /   /    /  \    ${S03}
${COL}${BOLD}            /   /    /    \    ${S04}
${COL}${BOLD}           /   /    /      \    ${S05}
${COL}${BOLD}          /   /    /   /\   \    ${S06}
${COL}${BOLD}         /   /    /   /  \   \    ${S07}
${COL}${BOLD}        /   /    /    \   \   \    ${S08}
${COL}${BOLD}       /   /    /      \   \   \    ${S09}
${COL}${BOLD}      /   /    /   /\   \   \   \    ${S10}
${COL}${BOLD}     /   /    /   /  \   \   \   \    ${S11}
${COL}${BOLD}    /   /    /   /    \   \   \   \    ${S12}
${COL}${BOLD}   /   /____/   /______\   \   \   \    ${S13}
${COL}${BOLD}  /                         \   \   \    ${S14}
${COL}${BOLD} /________________________   \   \   \    ${S15}
${COL}${BOLD}                          \   \   \  /    ${S16}
${COL}${BOLD}   ________________________\   \   \/    ${S17}
${COL}${BOLD}   \                            \       ${S18}
${COL}${BOLD}    \____________________________\     ${S19}
${COL}${BOLD}				      ${S20}\n\n\n"

exit ${SUCCESS}
