#!/bin/bash
#: Title:       : wami
#: Author       : clewsy (clews.tech)
#: Description  : Pull information regarding the external ip address
#:              : (from ifconfig.co), format, then print to screen.
#: Options      : -4    Resolve names to IPv4 addresses only.
#:              : -6    Resolve names to IPv6 addresses only.

# Exit codes.
SUCCESS=0
BAD_OPTION=1    # Invalid option entered.
NO_CURL=2       # curl not found.
CURL_FAIL=3     # curl returned an error.

# Text formatting codes.
RED="\033[00;31m"
BOLD="\033[01;37m"
RESET="\033[00;0m"

# Usage
USAGE="
${0##*/}: Determine external IP address and location information.

Usage: ${BOLD}${0##*/} <option>${RESET}

Options:
-4 : Attepmt to resolve names to IPv4 address only.
-6 : Attepmt to resolve names to IPv6 address only.
-h : Print this usage and exit.
"

# Get command line options and set appropriate flags.
while getopts '46h' OPTION; do      ## getopts to identify options
    case "$OPTION" in
        4)  IPV="--ipv4" ;;             ## Force curl to resolve to IPv4 only.
        6)  IPV="--ipv6" ;;             ## Force curl to resolve to IPv6 only.
        h)  printf "%b" "${USAGE}\n"    ## Print help (usage).
            exit ${SUCCESS} ;;          ## Exit successfully.
        ?)  printf "%b" "${USAGE}\n"    ## Invalid option, show usage.
            exit ${BAD_OPTION} ;;       ## Exit.
    esac
done
shift $((OPTIND -1))    ## Ensures only non-option arguments are considered
                        ## when referencing $#, #* and $n.

# Define the preferred temp file location.  Default to the current directory.
TEMP_FILE="/tmp/wami_tempfile"
if [ ! -w "${TEMP_FILE%/*}" ]; then TEMP_FILE="./wami_tempfile"; fi

# Check if curl is not installed.
if ! command -v curl >> /dev/null ; then
    printf "\n%bError%b: curl is not installed." "${RED}" "${RESET}"
    printf "\nQuitting.\n\n"
    exit ${NO_CURL}
fi

# Define options to use with curl command.
CURL_OPTIONS=(
    --silent
    --connect-timeout 5
    --max-time 10
    ${IPV}
)

# Pull the ip info.  Write to temp file.
printf "\nPulling data from \"ifconfig.co\"...\n"
if ! curl "${CURL_OPTIONS[@]}" --output "${TEMP_FILE}" ifconfig.co/json; then
    printf "\n%bError%b: Failed to reach \"ifconfig.co\"." "${RED}" "${RESET}"
    printf "\nQuitting.\n\n"
    if [[ -f "${TEMP_FILE}" ]]; then rm "${TEMP_FILE}"; fi
    exit ${CURL_FAIL}
fi

# Parse the ip info.
IP=$(           grep -m 1 "ip"      "${TEMP_FILE}")
HOST_NAME=$(    grep "hostname"     "${TEMP_FILE}")
ORG=$(          grep "asn_org"      "${TEMP_FILE}")
COUNTRY_CODE=$( grep "country_iso"  "${TEMP_FILE}")
COUNTRY=$(      grep -m 1 "country" "${TEMP_FILE}")
REGION=$(       grep "region_name"  "${TEMP_FILE}")
CITY=$(         grep "city"         "${TEMP_FILE}")
POST_CODE=$(    grep "zip_code"     "${TEMP_FILE}")
TIMEZONE=$(     grep "time_zone"    "${TEMP_FILE}")
LATITUDE=$(     grep "latitude"     "${TEMP_FILE}")
LONGITUDE=$(    grep "longitude"    "${TEMP_FILE}")

# Remove trailing characters.       # Remove leading characters.
IP=${IP%\",};                       IP=${IP##*\"}
HOST_NAME=${HOST_NAME%\",};         HOST_NAME=${HOST_NAME##*\"}
ORG=${ORG%\",};                     ORG=${ORG##*\"}
COUNTRY_CODE=${COUNTRY_CODE%\",};   COUNTRY_CODE=${COUNTRY_CODE##*\"}
COUNTRY=${COUNTRY%\",};             COUNTRY=${COUNTRY##*\"}
REGION=${REGION%\",};               REGION=${REGION##*\"}
CITY=${CITY%\",};                   CITY=${CITY##*\"}
POST_CODE=${POST_CODE%\",};         POST_CODE=${POST_CODE##*\"}
TIMEZONE=${TIMEZONE%\",};           TIMEZONE=${TIMEZONE##*\"}
LATITUDE=${LATITUDE%,};             LATITUDE=${LATITUDE##*\ }
LONGITUDE=${LONGITUDE%,};           LONGITUDE=${LONGITUDE##*\ }

printf "\n" # Start main output after a line break.
if [ -n "${IP}" ];              then printf "%bIP:%b------------ %s\n" "${BOLD}" "${RESET}" "${IP}";            fi
if [ -n "${HOST_NAME}" ];       then printf "%bHostname:%b------ %s\n" "${BOLD}" "${RESET}" "${HOST_NAME}";     fi
if [ -n "${ORG}" ];             then printf "%bOrganisation:%b-- %s\n" "${BOLD}" "${RESET}" "${ORG}";           fi
if [ -n "${COUNTRY_CODE}" ];    then printf "%bCountry Code:%b-- %s\n" "${BOLD}" "${RESET}" "${COUNTRY_CODE}";  fi
if [ -n "${COUNTRY}" ];         then printf "%bCountry:%b------- %s\n" "${BOLD}" "${RESET}" "${COUNTRY}";       fi
if [ -n "${REGION}" ];          then printf "%bRegion:%b-------- %s\n" "${BOLD}" "${RESET}" "${REGION}";        fi
if [ -n "${CITY}" ];            then printf "%bCity:%b---------- %s\n" "${BOLD}" "${RESET}" "${CITY}";          fi
if [ -n "${POST_CODE}" ];       then printf "%bPost Code:%b----- %s\n" "${BOLD}" "${RESET}" "${POST_CODE}";     fi
if [ -n "${TIMEZONE}" ];        then printf "%bTimezone:%b------ %s\n" "${BOLD}" "${RESET}" "${TIMEZONE}";      fi
if [ -n "${LATITUDE}" ];        then printf "%bLatitude:%b------ %s\n" "${BOLD}" "${RESET}" "${LATITUDE}";      fi
if [ -n "${LONGITUDE}" ];       then printf "%bLongitude:%b----- %s\n" "${BOLD}" "${RESET}" "${LONGITUDE}";     fi
printf "\n" # Finish main output with a line break.

rm "${TEMP_FILE}"   # Clean up.

exit ${SUCCESS}
